### ISSUE TITLE
add admin userID to init_settings.yml

### ISSUE THREAD

**Issue by dimonDDL** [ThatRedKite/thatkitebot#10]
Add a setting for setting the admin of the bot who can execute `+kill` and such to init_settings.yml

**Comment by ThatRedKite** [comment]
Only the bot owner should be able to kill it in my opinion

**Comment by dimonDDL** [comment]
I mean the person spinning up an instance of it on a server sure sounds to me like an owner.

**Comment by ThatRedKite** [comment]
which should be the bot owner? It already checks for the owner of the discord bot itself

**Comment by dimonDDL** [comment]
didn't know that I thought it was hard coded)
