### ISSUE TITLE
Fix Listener Cog

### ISSUE THREAD

**Issue by Caraffa-git** [ThatRedKite/thatkitebot#107]
Listener doesn't catch  `commands.CheckFailure` exception. I noticed this because of the check in SlashCommandGroup from #104 (info.py:209)    
```
@commands.Cog.listener()
async def on_command_error(self, ctx: commands.Context, error):
```

**Comment by ThatRedKite** [comment]
Well you are supposed to have a check failure error handler for commands that can throw one.

**Comment by Caraffa-git** [comment]
:raised_eyebrow: Then why there is whole separate listener cog with "global error handler" and there is no other code that would handle them
