### ISSUE TITLE
add a simple RC filter

### ISSUE THREAD

**Issue by Cuprum77** [ThatRedKite/thatkitebot#3]
should be possible to generate a simple rc filter with +filter r= c=
if possible it would be nice if it returned a bodeplot as well but thats more complicated

math is F_cutoff = 1/RC

**Comment by dimonDDL** [comment]
[This](https://stackoverflow.com/questions/25191620/creating-lowpass-filter-in-scipy-understanding-methods-and-units) can actually generate plots pretty well.

**Comment by ThatRedKite** [comment]
I will look into it
