### ISSUE TITLE
Fix inconsistancy on `+` and `/` commands

### ISSUE THREAD

**Issue by GhostDog98** [ThatRedKite/thatkitebot#98]
This is quite confusing, for example, the info command only works if you do `/info` but not `+info`, but the help command only works if you do `+help` but not if you do `/help` command!?!?!?

(p.s. this isn't me just bitching, it's also kinda a todo list for if i wanna do stuff for kitebot :trollface:)

**Comment by ThatRedKite** [comment]
That is because /info is a completely different kind of command. Slash commands are different from prefixed commands
