### ISSUE TITLE
Image commands do not properly work with new discord embed system

### ISSUE THREAD

**Issue by GhostDog98** [ThatRedKite/thatkitebot#99]
Recently discord added a feature where you can add multiple photos with a single message, such as below:
![image](https://github.com/ThatRedKite/thatkitebot/assets/46546505/41a2dcf5-2fc9-4d65-a0ff-ff1e7cbab959)
However, if we are to use any of the kitebot commands for manipulating images on these messages, it only applies to the first attached image:
![image](https://github.com/ThatRedKite/thatkitebot/assets/46546505/8814d471-3298-40ab-b4ec-3e602e8f3655)
This is the same for all of the image commands I tested (only 3).

**Comment by ThatRedKite** [comment]
This was kind of a design decision, because there is no good way of specifying which image to process, so it will always default to the first
